-- Generated from APIJSON-Demo/MySQL for KingbaseES V9R1 MySQL compatibility mode.
-- INSERT values are preserved; MySQL backslash escapes are rendered as standard SQL.
SET search_path TO public;
SET client_encoding TO 'UTF8';
SET standard_conforming_strings TO on;

BEGIN;
-- MySQL dump 10.13  Distrib 8.0.42, for macos15 (arm64)
--
-- Host: apijson.cn    Database: sys
-- ------------------------------------------------------
-- Server version	8.4.5

--
-- Table structure for table `Script`
--

DROP TABLE IF EXISTS `Script`;

CREATE TABLE `Script` (
  `id` bigint GENERATED BY DEFAULT AS IDENTITY (START WITH 1738490404346) NOT NULL,
  `userId` bigint NOT NULL DEFAULT '0',
  `testAccountId` bigint NOT NULL DEFAULT '0',
  `chainGroupId` bigint NOT NULL DEFAULT '0',
  `chainId` bigint NOT NULL DEFAULT '0',
  `documentId` bigint NOT NULL DEFAULT '0',
  `simple` smallint NOT NULL DEFAULT '0',
  `ahead` smallint NOT NULL DEFAULT '0',
  `title` varchar(100) DEFAULT NULL,
  `name` varchar(100) NOT NULL,
  `Script` text NOT NULL,
  `date` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `detail` varchar(1000) DEFAULT NULL,
  `randomId` bigint NOT NULL DEFAULT '0',
  PRIMARY KEY (`id`),
  CONSTRAINT `Script_id_UNIQUE` UNIQUE (`id`)
);

--
-- Dumping data for table `Script`
--
INSERT INTO `Script` VALUES (1,0,0,0,0,0,0,0,NULL,'getType','function getType(curObj, key) {
    var val = curObj == null ? null : curObj[key];
    return val instanceof Array ? "array" : typeof val;
}','2022-11-16 16:01:23',NULL,0),(2,0,0,0,0,0,0,0,NULL,'isContain','function isContain(curObj, arrKey, valKey) {
    var arr = curObj == null ? null : curObj[arrKey];
    var val = curObj == null ? null : curObj[valKey];
    return arr != null && arr.indexOf(val) >=0;
}','2022-11-16 16:02:48',NULL,0),(3,0,0,0,0,0,1,0,NULL,'init','var i = 1;
"init done "  + i;','2022-11-16 16:41:35',NULL,0),(4,0,0,0,0,0,0,0,NULL,'length','function length(curObj, key) {
    var val = curObj == null ? null : curObj[key];
    return val == null ? 0 : val.length;
}','2022-11-16 17:18:43',NULL,0),(1670877914051,82001,0,0,0,0,1,1,'执行脚本 2022-12-13 04:44','','function assert(assertion, msg) {
     if (assertion === true) {
         return
     }
     if (msg == null) {
         msg = ''assert failed! assertion = '' + assertion
     }

     if (isTest) {
         console.log(msg)
         alert(msg)
     } else {
         throw new Error(msg)
     } 
}  

if (isTest) {
     assert(true)
     assert(false)
     assert(true, ''ok'')
     assert(false, ''data.User shoule not be null!'') 
}

function getCurAccount() {
  return App.getCurrentAccount()
}','2022-12-12 20:45:14',NULL,0),(1670878495619,82001,82002,0,0,0,1,0,'执行脚本 2022-12-13 04:54','','function getCurAccount() {
  return App.getCurrentAccount()
}','2022-12-12 20:54:55',NULL,0),(1670878529042,82001,82001,0,0,0,1,1,'执行脚本 2022-12-13 04:55','','function getCurAccount() {
  return App.getCurrentAccount()
}','2022-12-12 20:55:29',NULL,0),(1670878622401,82001,82003,0,0,0,1,0,'执行脚本 2022-12-13 04:57','','if (isPre) {
  header[''my-header''] = ''test''
}','2022-12-12 20:57:02',NULL,0),(1670885503909,82001,0,0,0,1657045372046,1,1,'执行脚本 2022-12-13 06:51','','if (isPre) {
  req.User.id = 82005
}','2022-12-12 22:51:43',NULL,0),(1670887211207,82001,0,0,0,1657045372046,1,0,'执行脚本 2022-12-13 07:20','','','2022-12-12 23:20:11',NULL,0),(1676368454070,82001,0,0,0,1546414192830,1,0,NULL,'casePost1546414192830','','2023-02-14 09:54:14',NULL,0),(1679282174670,82001,0,0,0,0,1,1,NULL,'到店系统查询','','2023-03-20 03:16:14',NULL,0),(1680660620759,82001,0,0,0,1511796155276,1,1,NULL,'casePre1511796155276','if (isPre) {
    console.log(''test pre script 4 /post/verify'')    
}
','2024-05-03 03:55:14',NULL,0),(1680660620760,82001,0,1716706529846,42,1511970009072,1,1,NULL,'casePre1511970009072','if (isPre) { console.log("test pre script") }','2024-09-08 16:00:15',NULL,0),(1680660620761,82001,0,1716706529846,42,1511970009072,1,0,NULL,'casePost1511970009072','console.log(''run post script'')','2024-09-08 16:00:32',NULL,0),(1680660620762,82001,0,1714209723275,2,1546414192830,1,1,NULL,'casePre1546414192830','','2024-11-28 02:10:39',NULL,0),(1738490311550,0,0,0,0,1560244940013,1,0,NULL,'casePost1560244940013','','2025-02-02 09:58:32',NULL,0),(1738490327734,0,0,0,0,0,1,0,NULL,'globalPost0','if (data != null) {
    delete data["sql:generate|cache|execute|maxExecute"]
}
','2025-02-02 09:58:48',NULL,0),(1738490404341,0,0,0,0,0,1,1,NULL,'globalPre0','req[''@explain''] = true','2025-02-02 10:00:04',NULL,0),(1738490404342,82001,0,0,0,0,1,1,NULL,'','','2025-03-11 08:54:24',NULL,0),(1738490404343,82001,0,0,0,1560737118846,1,0,NULL,'casePost1560737118846','','2025-12-15 05:16:55',NULL,0),(1738490404344,82001,0,0,0,0,1,1,NULL,'globalPre0','function assert(b, msg) { 
  if (b) { 
     return; 
  } function assert(b, msg) { 
  if (b) { 
     return; 
  } 
  throw new Error(msg || ''断言失败''); 
}; 

App.assert = assert;
  throw new Error(msg || ''断言失败''); 
}; 
App.assert = assert;','2026-02-13 07:18:02',NULL,0),(1738490404345,82001,0,0,0,1703475322145,1,0,NULL,'casePost1703475322145','var data = data || res.data || {}
var methodArgs = data.methodArgs || []; 
var a = (methodArgs[0] || {}).value; 
var b = (methodArgs[1] || {}).value;
App.assert(data[''return''] == Math.pow(a, b), data[''return''] + '' != Math.pow('' + a + '', '' + b + '') = '' + Math.pow(a, b)); // + ''\n\n'' + JSON.stringify(data, null, 4));','2026-02-13 07:19:21',NULL,0);
-- Dump completed on 2026-02-22  3:16:14
COMMIT;
