-- KingbaseES V9R1C10 Oracle 模式兼容脚本
-- 数据来源：APIJSON-Demo/Oracle；INSERT 数据载荷保持不变。
-- 建议在 KStudio 中以 UTF-8 编码、Oracle 模式连接执行。

-- db3 是原 Oracle 脚本使用的模式；不存在时创建。
CREATE SCHEMA IF NOT EXISTS db3;

DROP TABLE IF EXISTS db3.CONTRACT;


create table db3.CONTRACT
(
	ID NUMBER not null
		primary key,
	CNT_NAME VARCHAR2(100),
	CNT_BUYER_NAME VARCHAR2(100),
	CNT_SELLER_NAME VARCHAR2(100)
);




INSERT INTO db3.CONTRACT (ID, CNT_NAME, CNT_BUYER_NAME, CNT_SELLER_NAME) VALUES (1, '合同名称', '买方名称', '卖方名称');
INSERT INTO db3.CONTRACT (ID, CNT_NAME, CNT_BUYER_NAME, CNT_SELLER_NAME) VALUES (2, '合同名称', '买方名称', '卖方名称');
INSERT INTO db3.CONTRACT (ID, CNT_NAME, CNT_BUYER_NAME, CNT_SELLER_NAME) VALUES (3, '合同名称', '买方名称', '卖方名称');
INSERT INTO db3.CONTRACT (ID, CNT_NAME, CNT_BUYER_NAME, CNT_SELLER_NAME) VALUES (4, '合同名称', '买方名称', '卖方名称');
INSERT INTO db3.CONTRACT (ID, CNT_NAME, CNT_BUYER_NAME, CNT_SELLER_NAME) VALUES (5, '合同名称', '买方名称', '卖方名称');
INSERT INTO db3.CONTRACT (ID, CNT_NAME, CNT_BUYER_NAME, CNT_SELLER_NAME) VALUES (6, '合同名称', '买方名称', '卖方名称');
INSERT INTO db3.CONTRACT (ID, CNT_NAME, CNT_BUYER_NAME, CNT_SELLER_NAME) VALUES (7, '合同名称', '买方名称', '卖方名称');
INSERT INTO db3.CONTRACT (ID, CNT_NAME, CNT_BUYER_NAME, CNT_SELLER_NAME) VALUES (8, '合同名称', '买方名称', '卖方名称');
INSERT INTO db3.CONTRACT (ID, CNT_NAME, CNT_BUYER_NAME, CNT_SELLER_NAME) VALUES (9, '合同名称', '买方名称', '卖方名称');
INSERT INTO db3.CONTRACT (ID, CNT_NAME, CNT_BUYER_NAME, CNT_SELLER_NAME) VALUES (10, '合同名称', '买方名称', '卖方名称');

commit;